

-- work with alter keyword



-- CREATE TABLE
CREATE TABLE "USER"
(
    NAME VARCHAR(100),
    EMAIL  VARCHAR(100) UNIQUE NOT NULL,
    USERNAME VARCHAR(100) UNIQUE NOT NULL

);


-- INSERT DATA

INSERT INTO "USER"(NAME, EMAIL, USERNAME)
    VALUES
        ('MORSALIN ISLAM', 'MORSALIN', 'DEV.MORSALIN@GMAIL.COM'),
        ('MOTIUR RAHMAN', 'MOTIUR', 'MOTIUR.GMAIL.COM');

SELECT * FROM "USER";

-- NOW WORKING WITH ALTER TABLE

-- ##### ADD COLUMN

ALTER TABLE "USER"
    ADD COLUMN PASSWORD VARCHAR(100) DEFAULT '12345' NOT NULL;

SELECT * FROM "USER";


-- RENAME COLUMN NAME

ALTER TABLE "USER"
    RENAME COLUMN PASSWORD TO "USER PASSWORD";


-- CHANGE DATA TYPE OR CHANGE SHAPE
ALTER TABLE "USER"
    ALTER COLUMN NAME TYPE VARCHAR(200);

-- DROP  COLUMN

ALTER TABLE "USER"
    DROP COLUMN USERNAME;

SELECT * FROM "USER";

-- SHOW DATA_DIRECTORY; -> SHOW DATA DIRECTORY

