

-- function can return value, procedure can't return value

-- PROCEDURE CREATION 

CREATE PROCEDURE DELETE_EMPLOYEE_BY_ID(PARAM_ID INT)
-- AVOID RETURNS HERE
LANGUAGE PLPGSQL 
AS 
$$
    BEGIN
        DELETE FROM EMPLOYEES 
            WHERE EMPLOYEE_ID = PARAM_ID;
    END 
$$;

CALL DELETE_EMPLOYEE_BY_ID(29);

SELECT * FROM EMPLOYEES;