


/*
    VIEW CREATION SYNTAX

    CREATE VIEW VIEW_NAME
        AS
        SELECT ...
        WHERE

    
    VIEW USING SYNTAX:
        SELECT COLUMN(S) FROM CREATED_VIEW => THIS WILL RETURN VIEW'S CREATED VIRTUAL TABLE
        

*/

SELECT * FROM EMPLOYEES;

CREATE VIEW EMPLOYEE_SALARY
    AS
        SELECT EMPLOYEE_NAME, SALARY FROM EMPLOYEES;



SELECT * FROM EMPLOYEE_SALARY;