USE LIBRARY;

SELECT MAX(PRICE) FROM BOOK;
SELECT MIN(PRICE) FROM BOOK;
SELECT NAME, PRICE FROM BOOK -- RETRIVE THE BOOK WITH HIGHEST PRICE
	WHERE PRICE = (SELECT MAX(PRICE) FROM BOOK);
    
-- NOW UPDATE THE THOSE BOOKS WHICH PRICE RANGE IS LOWEST PRICE TO LOWEST PRICE + 100 WITH HIGHEST PRICE - 100

SET SQL_SAFE_UPDATES = FALSE;

SELECT MIN(PRICE) FROM BOOK INTO @MinPrice;
SELECT MAX(PRICE) FROM BOOK INTO @MaxPrice;

UPDATE BOOK
	SET PRICE = @MaxPrice - 100
    WHERE PRICE BETWEEN @MinPrice AND @MinPrice - 100;
    
SET SQL_SAFE_UPDATES = TRUE;

-- To same things without using variable

SET SQL_SAFE_UPDATES = FALSE;
UPDATE BOOK as B
	JOIN(
		Select 
			MIN(Price) as minPrice,
            MAX(Price) as maxPrice
		From Book
    ) AS PriceLimit
    ON
    B.Price Between PriceLimit.minPrice AND PriceLimit.maxPrice - 100
    SET B.Price = PriceLimit.maxPrice - 100;
    

SELECT * FROM BOOK;