USE LIBRARY;

-- WORKING WITH AND
SELECT * FROM BOOK
	WHERE PRICE > 500 AND PRICE < 700; -- RETRIVE BOOK WHICH PRICE GREATER THEN 500 AND LESS THEN 700

-- WORKING WITH OR

SELECT * FROM BOOK
	WHERE ID < 5 OR PRICE > 500; -- RETRIVE BOOK WHICH ID LESS THEN 5 OR PRICE GRATER THEN 500
    