-- OBJECTIVE WORK WITH SQL JOIN
CREATE DATABASE CUSTOMER_ORDER; -- CRATE A NEW DATABASE NAME CUSTOMER_ORDER
USE CUSTOMER_ORDER; -- USE THIS DATABASE


-- CREATE ORDERS TABLE
CREATE TABLE ORDERS(
	ORDERID INT auto_increment PRIMARY KEY,
    CUSTOMERID INT NOT NULL,
    ORDERDATE DATE
);

-- CREATE CUSTOMERS TABLE
CREATE TABLE CUSTOMERS(
	CUSTOMERID INT PRIMARY KEY,
    NAME VARCHAR(100),
    COUNTRY VARCHAR(80)
    
);

-- INSERT NEW DATA IN ORDERS TABLE
INSERT INTO ORDERS(ORDERID, CUSTOMERID, ORDERDATE)
	VALUES
    (101, 2, '1996-09-18'),
    (102, 3, '1996-09-19'),
    (103, 4, '1996-09-20');
    

-- INSERT NEW DATA IN CUSTOMERS TABLE
INSERT INTO CUSTOMERS(CUSTOMERID, NAME, COUNTRY)
	VALUES
    (2, 'MORSALIN', 'BANGALDESH'),
    (3, 'MOTIUR RAHMAN', 'US'),
    (4, 'RUKUNUZZAMAN', 'UK');
    
SELECT * FROM CUSTOMERS;
    
