

USE LIBRARY;

-- CHAR WILDCARD
SELECT * FROM BOOK
	WHERE PRICE LIKE ('9_0'); -- PRICE MAY 910, 920, 930... 990 
    -- CHAR WILDCARD MAY BE NUMBER
    
-- % WILDCARD

SELECT * FROM BOOK
	WHERE NAME LIKE('I%'); -- BOOK  NAME WHICH START WITH I WILL SELECT
    
-- WILDCARD WITH OPERATOR


SELECT * FROM BOOK
	WHERE NAME LIKE('%I%') OR NAME LIKE('C__c_i%') OR NAME LIKE('%STACK%');
    -- NAME MAY BE ___i___ OR C--c-i____ OR ____STACK____
    
    